export enum postTypes {
  FETCH_POST_REQUEST = "FETCH_POST_REQUEST",
  FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE = "FETCH_POST_FAILURE",
  ADD_MY_FAV_POST="ADD_MY_FAV_POST",
  REMOVE_MY_FAV_POST="REMOVE_MY_FAV_POST"
}
  